### ISSUE TITLE
Cannot go back to ongoing game from introduction

### ISSUE THREAD

**Issue by Garretist** [gotling/terraforming-mars-companion#7]
After starting a new game and navigation to the Config tab and clicking the Introduction button I cannot choose to go back to the game. I can only choose to start a new game or go to the guide.

This is the screen I'm presented with:
![Screenshot_20241115-224948](https://github.com/user-attachments/assets/1118e438-8d74-4cea-b430-bd1e3824a6a6)

A side note:
In general it felt as if it was hard to navigate back to an ongoing game. Should that be possible after "exiting" the game screen?

**Comment by gotling** [comment]
Hi! Thank you for the report.

I suspect what happened is that you created a new game but did not do anything.

If any action has been made on a game, like adding credits, the intro screen will show that you have an ongoing game and on what generation and display a Continue button.

**Comment by Garretist** [comment]
Yes, you're right! My bad.
